version: "3.7"

services:

  web80:
    image: nginx:1.21-alpine
    expose:
      - 80
      - 443
    volumes:
      - .:/var/www/html
      - ./docker/site.conf:/etc/nginx/conf.d/site.conf
      - ~/Sites/docker/nginx-proxy/ssl:/etc/nginx/certs
    container_name: host_laravelproject
    environment:
       VIRTUAL_HOST: "laravelproject.local.dock"
       VIRTUAL_PROTO: "https"
       VIRTUAL_PORT: 443
    depends_on:
      - php80

  php80:
    image: php-80-fpm:v1
    container_name: host_laravelproject_fpm
    volumes:
      - .:/var/www/html
      - ./docker/php-8.0.ini:/usr/local/etc/php/php.ini

networks:
  default:
    name: nginx-proxy