version: "3.2"

services:
  php55:
    image: php-55-fpm:v1
    container_name: host_apache_fpm
    volumes:
      - ./public/:/var/www/html/
  apache55:
    image: host_apache:v1
    container_name: host_apache
    depends_on:
    - host_apache_fpm
    expose:
      - 80
    environment:
       VIRTUAL_HOST: "apache.local.dock"
    volumes:
      - ./apache/apache.local.conf:/usr/local/apache2/conf/apache.local.conf
      - ./public/:/var/www/html/

networks:
  default:
      name: nginx-proxy